/*
 * Main.java
/**
 *
 * @author  __USER__
 */
import java.sql.*;

@SuppressWarnings("serial")
public class LoginWindow extends javax.swing.JFrame {

	/** Creates new form Main */
	public LoginWindow() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jButton1 = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jButton2 = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jPasswordField1 = new javax.swing.JPasswordField();

		setDefaultCloseOperation(3);

		jButton1.setText("Connect");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel1.setText("Connection Check");

		jTextField1.setText("Login");

		jButton2.setText("Create New User");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jLabel2.setText("Log Into Your Account");

		jPasswordField1.setText("Password");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(88, Short.MAX_VALUE)
								.addComponent(jTextField1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										98,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addComponent(jPasswordField1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										104,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(97, 97, 97))
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(243, Short.MAX_VALUE)
								.addComponent(jButton2).addContainerGap())
				.addGroup(
						layout.createSequentialGroup().addGap(124, 124, 124)
								.addComponent(jLabel2)
								.addContainerGap(129, Short.MAX_VALUE))
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(150, Short.MAX_VALUE)
								.addComponent(jButton1).addGap(165, 165, 165))
				.addGroup(
						layout.createSequentialGroup().addGap(133, 133, 133)
								.addComponent(jLabel1)
								.addContainerGap(151, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel2)
								.addGap(65, 65, 65)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING,
												false)
												.addComponent(jTextField1)
												.addComponent(
														jPasswordField1,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														25, Short.MAX_VALUE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jButton1)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jLabel1)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										64, Short.MAX_VALUE)
								.addComponent(jButton2).addContainerGap()));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		WindowController.showusercreatorwindow();
		WindowController.closeloginwindow();
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {

		String loginTB = jTextField1.getText();
		String passwordTB = jPasswordField1.getText();

		Connection conn = DbController.dbconnect();

		if (DbController.login(conn, loginTB, passwordTB)) {
			WindowController.showmainwindow(loginTB);
			WindowController.closeloginwindow();
		} else {
			jLabel1.setText("Wrong Login or Password");
		}

		try {
			conn.close();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPasswordField jPasswordField1;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}