import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.swing.DebugGraphics;

import com.mysql.jdbc.Connection;

@SuppressWarnings("serial")
public class MainWindow extends javax.swing.JFrame {
	String m_loggedas;
	List<String> friends = new ArrayList<String>();

	/** Creates new form mainwindow */
	public MainWindow(String loggedas) {

		m_loggedas = loggedas;
		java.sql.Connection conn = DbController.dbconnect();
		friends = DbController.getfriends(conn, loggedas);

		try {
			conn.close();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		initComponents();
		int length;
		length = friends.size();
		for(int i=0;i<length;i++)
		{
			System.out.println(friends.get(i));
			list1.addItem("test");
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

desktopPane = new javax.swing.JDesktopPane();
menuBar = new javax.swing.JMenuBar();
fileMenu = new javax.swing.JMenu();
exitMenuItem = new javax.swing.JMenuItem();
jMenuItem1 = new javax.swing.JMenuItem();
helpMenu = new javax.swing.JMenu();
aboutMenuItem = new javax.swing.JMenuItem();

setDefaultCloseOperation(3);

desktopPane.setName("");

fileMenu.setText("File");

exitMenuItem.setText("Exit");
exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
exitMenuItemActionPerformed(evt);
}
});
fileMenu.add(exitMenuItem);

jMenuItem1.setText("Change User");
jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jMenuItem1ActionPerformed(evt);
}
});
fileMenu.add(jMenuItem1);

menuBar.add(fileMenu);

helpMenu.setText("Help");

aboutMenuItem.setText("About");
aboutMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
public void mouseClicked(java.awt.event.MouseEvent evt) {
aboutMenuItemMouseClicked(evt);
}
});
aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
aboutMenuItemActionPerformed(evt);
}
});
helpMenu.add(aboutMenuItem);

menuBar.add(helpMenu);

setJMenuBar(menuBar);

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
);
layout.setVerticalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
);

pack();
}// </editor-fold>

	//GEN-END:initComponents

	private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {
		DbController.logout(m_loggedas);
		WindowController.showloginwindow();
		WindowController.closemainwindow();
	}

	private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
		WindowController.showaboutbox(m_loggedas);
		WindowController.closemainwindow();
	}

	private void aboutMenuItemMouseClicked(java.awt.event.MouseEvent evt) {

	}

	private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
		DbController.logout(m_loggedas);
		System.exit(0);
	}//GEN-LAST:event_exitMenuItemActionPerformed

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JMenuItem aboutMenuItem;
	private javax.swing.JDesktopPane desktopPane;
	private javax.swing.JMenuItem exitMenuItem;
	private javax.swing.JMenu fileMenu;
	private javax.swing.JMenu helpMenu;
	private javax.swing.JMenuItem jMenuItem1;
	private java.awt.List list1;
	private javax.swing.JMenuBar menuBar;
	// End of variables declaration//GEN-END:variables

}