package windows;
import java.sql.Connection;
import java.sql.SQLException;

import javax.swing.JOptionPane;

import controllers.DbController;
import controllers.WindowController;

/*
 * AddFriend.java
 *
 * Created on __DATE__, __TIME__
 */

/**
 *
 * @author  __USER__
 */
public class AddFriend extends javax.swing.JFrame {
	String m_loggedas;

	/** Creates new form AddFriend */
	public AddFriend(String loggedas) {
		initComponents();

		m_loggedas = loggedas;
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jTextField1 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();

		setDefaultCloseOperation(3);

		jTextField1.setText("Enter Friend Login Here");
		jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jTextField1MouseClicked(evt);
			}
		});
		jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				jTextField1FocusGained(evt);
			}

			public void focusLost(java.awt.event.FocusEvent evt) {
				jTextField1FocusLost(evt);
			}
		});

		jButton1.setText("Add");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("Back To MainWindow");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jTextField1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		201,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		113,
																		Short.MAX_VALUE)
																.addComponent(
																		jButton1)
																.addContainerGap())
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addComponent(
																		jButton2)
																.addGap(110,
																		110,
																		110))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jLabel1)
																.addContainerGap(
																		388,
																		Short.MAX_VALUE)))));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButton1)
												.addComponent(
														jTextField1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jLabel1)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										33, Short.MAX_VALUE)
								.addComponent(jButton2).addContainerGap()));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {
		if (jTextField1.getText().isEmpty())
			jTextField1.setText("Enter Friends Login");
	}

	private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {
		jTextField1.setText("");
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		Connection conn = DbController.dbconnect();
		if(DbController.checkifexist(conn, jTextField1.getText(), "Login"))
		{
			boolean test = DbController.addfriend(conn, m_loggedas, jTextField1.getText());
			try {
				conn.close();
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			if (test)
			{
				jLabel1.setText("Dodano do znajomych");

				JOptionPane.showMessageDialog(null, "Dodano do znajomych");
				
			}
			else
			{
				jLabel1.setText("Nie udalo sie dodac do znajomych");
				JOptionPane.showMessageDialog(null, "Nie udalo sie dodac do znajomych");
				
			}
		}
		else
			jLabel1.setText("Uzytkownik nie istnieje");
			
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		WindowController.showmainwindow(m_loggedas);
		WindowController.closeaddfriendwindow();
	}

	private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {
		jTextField1.setText("");
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}